# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AzV62AZ6S2XGqQlHjxxCJNubrC3RkbDJ
"""

import math

results = {}

# Function to add two numbers
def add(x, y):
    return x + y

# Function to subtract two numbers
def subtract(x, y):
    return x - y

# Function to multiply two numbers
def multiply(x, y):
    return x * y

# Function to divide two numbers
def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y

# Function to calculate the square of a number
def square(x):
    return x ** 2

# Function to calculate the square root of a number
def square_root(x):
    if x < 0:
        return "Invalid input"
    return math.sqrt(x)

# Function to calculate x raised to the power of y
def power(x, y):
    return x ** y

while True:
    print("Options:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Square")
    print("6. Square Root")
    print("7. Power")
    print("8. Store Result")
    print("9. Recall Result")
    print("10. Quit")

    choice = input("Enter the number for your choice: ")

    if choice == "10":
        break
    elif choice in ("1", "2", "3", "4", "5", "6", "7"):
        if choice in ("1", "2", "3", "4", "7"):
            num1 = float(input("Enter the first number: "))
            num2 = float(input("Enter the second number: "))
        else:
            num1 = float(input("Enter a number: "))

        if choice == "1":
            result = add(num1, num2)
        elif choice == "2":
            result = subtract(num1, num2)
        elif choice == "3":
            result = multiply(num1, num2)
        elif choice == "4":
            result = divide(num1, num2)
        elif choice == "5":
            result = square(num1)
        elif choice == "6":
            result = square_root(num1)
        elif choice == "7":
            power_exp = float(input("Enter the exponent: "))
            result = power(num1, power_exp)

        print("Result:", result)
        results[choice] = result

    elif choice == "8":
        key = input("Enter a key to store the result: ")
        if key in results:
            print("Key already exists. Overwriting.")
        results[key] = result
        print("Result stored with key:", key)

    elif choice == "9":
        key = input("Enter the key to recall the result: ")
        if key in results:
            print("Recalled result:", results[key])
        else:
            print("Key not found.")
    else:
        print("Invalid input. Please enter a valid option.")